_BASE_: video_maskformer2_R50_bs16_8ep_voca.yaml
MODEL:
  WEIGHTS: ""
  PER_REGION:
    DENSE_SUPERVISE: True
    PLAIN_LOSS_WEIGHT: 2.0
    DROPOUT: 0.5
  KD:
    STU_SOURCE: 'prior'
    TEC_SOURCE: 'attn_l'
    KD_WEIGHT: 2.0
    TEXT_KD_WEIGHT: -1.0
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.0001
  STEPS: (4000,)
  MAX_ITER: 6000
INPUT:
  DATASET_MAPPER_NAME: "vipseg_kd"    # todo

# MODEL.PER_REGION.DROPOUT 0.75  SOLVER.MAX_ITER 3000 SOLVER.STEPS (2000,)