_BASE_: maskformer2_R50_bs16_50ep_voca_ground_perRegion_syn.yaml
MODEL:
  WEIGHTS: "pretrained/R-50.pkl"
  RESNETS:
    DEPTH: 50
    STEM_TYPE: "basic"  # not used
    STEM_OUT_CHANNELS: 64
    STRIDE_IN_1X1: False
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
    # NORM: "SyncBN"
    RES5_MULTI_GRID: [1, 1, 1]  # not used
  BACKBONE:
    FREEZE_AT: 0
    NAME: "build_resnet_backbone"