# Copyright (c) Facebook, Inc. and its affiliates.
from .maskformer_transformer_decoder import StandardTransformerDecoder
from .mask2former_transformer_decoder import MultiScaleMaskedTransformerDecoder
from .mask2former_transformer_decoder_voca import MultiScaleMaskedTransformerDecoderVoca